### PR TITLE
close the cursor as soon as possible

### PR DESCRIPTION
**Pull request by peterbe**
The reason for this change is quite complex and something I've only been able to "test" (there are no unit tests) in MySQL but then again MySQL is the only one famous for having this annoying problem (http://dev.mysql.com/doc/refman/5.0/en/gone-away.html)

Basically, what happens is that even though nothing goes wrong I get this on stdout::

```
    Exception _mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
    in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x1025c1250>> ignored
```

After **a lot** of searching in the pdb trenches I think I figured out what it was. 

We use the cursor to execute something (e.g. "ALTER TABLE ...") but we don't care about any of the results. Then, nashvegas proceeds with a bunch of other things that might take time (e.g. executing post sync signals) and once all of that is done the objects are torn down and collected and when it does this, the cursor.**del** method is executed just before the python process shuts down and returns to the OS. Inside `cursor.__del__` (see code below) it first exhausts what's been fetched and deletes it but because this happens such a long time since the cursor was executed you get that dreaded error (it's actually trapped as just a warning my MySQLdb). 

The relevant code in MySQLdb/cursor.py:

```
    def __del__(self):
        self.close()
        self.errorhandler = None
        self._result = None

    def close(self):
        """Close the cursor. No further queries will be possible."""
        if not self.connection: return
        while self.nextset(): pass
        self.connection = None

    def nextset(self):
        if self._executed:
            self.fetchall()         
        del self.messages[:]

    db = self._get_db()
        nr = db.next_result()    # this is where MySQLdb barfs the exception 
        if nr == -1:
            return None
        self._do_get_result()
        self._post_get_result()
        self._warning_check()
        return 1
```

Like I said the exception is swallowed but we've experienced other weird undeterministic exceptions and errors with nashvegas and MySQL and I think it might help to at least use the dbapi properly as that makes things less likely to cause trouble when wrapped in Django's transaction magic clothing.

### CODE REVIEW

**Comment by paltman** [comment]
I really appreciate the pull request and the detailed write up and explanation.  I don't currently use MySQL anywhere but I do remember seeing this exception from time to time when I used to use MySQL in other environments (still Django but not nashvegas).  I'll make some time in the coming week or so to test this out on my existing project (Postgres) just to make sure it doesn't regress and then I'll pull and do a release.

Thanks!

**Comment by peterbe** [comment]
Thanks. yeah, don't ask me why we're using MySQL when there is Postgres :) 

Most of our problems we have with nashvegas + mysql are ultra weird and incredibly hard to reproduce. I think two titans are fighting for the attention of transaction management (django 1 and mysql 1) and somewhere there things go wrong sometimes. 

Check out this one for example: http://jhonjairoroa87.blogspot.com/2011/03/mysql-operationalerror-error-on-rename.html

**Comment by paltman** [comment]
So does this solve #26 as well? They seem like the same error message.

I apologize for the delay in dealing with this but will try my best to get your fix merged, tested, released this week.

**Comment by peterbe** [comment]
I honestly don't know if it solves #26 because the error we get there is non-deterministic. It's not unlikely it'll fix it because I suspect lingering cursors might be the reason.

**Comment by peterbe** [comment]
Any progress on looking at the pull request? It's a shame that it's not possible to make a reproduce-able case we can prove with a unit test but I think that it at least is more complete this way.

**Comment by paltman** [comment]
I merged this manually and tagged/released 0.6.4 (now on pypi)

**Comment by peterbe** [comment]
Thanks! When time allows I'm going to upgrade us and see if it removes some of the weirdness problems we've had with mysql.

**Pull request closed without merging**
